### ISSUE TITLE
ReemKufiInk crashes pyftsubset

### ISSUE THREAD

**Issue by rsheeter** [fonttools/fonttools#2438]
```
pyftsubset --text=duck --output-file=/tmp/reem.otf ReemKufiInk-Bold.otf

Traceback (most recent call last):
  File "/tmp/venv/bin/pyftsubset", line 8, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 3104, in main
    subsetter.subset(font)
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2908, in subset
    self._subset_glyphs(font)
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2846, in _subset_glyphs
    retain = table.subset_glyphs(self)
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/subset/__init__.py", line 2086, in subset_glyphs
    colorGlyphsV1 = unbuildColrV1(self.table.LayerList, self.table.BaseGlyphList)
  File "/tmp/venv/lib/python3.9/site-packages/fontTools/colorLib/unbuilder.py", line 6, in unbuildColrV1
    unbuilder = LayerListUnbuilder(layerV1List.Paint)
AttributeError: 'NoneType' object has no attribute 'Paint'
```

TTX handles the font just fine. File from https://github.com/aliftype/reem-kufi/commits/colr-v1 at 93d6dcd693ae42bb4295701e88a07cc4d04db73c

**Comment by rsheeter** [comment]
Summon @anthrotype

**Comment by anthrotype** [comment]
Oh.. the LayerList is optional so we should check is not None. Strange that the font makes no use of PaintColrLayers, but still valid and subsetter should be fixed

**Comment by khaledhosny** [comment]
> Strange that the font makes no use of PaintColrLayers

Yes, it is a placeholder font (all COLRv1 layers are single layers with solid colors)

**Comment by rsheeter** [comment]
I love that summoning Cosimo actually worked. And we found a bug, win/win!

**Comment by rsheeter** [comment]
Original pyftsubset command does now pass but other use still crashes; reopening.

```
  File "fontTools/subset/__init__.py", line 2908, in subset
    self._closure_glyphs(font)
  File "fontTools/subset/__init__.py", line 2788, in _closure_glyphs
    font[table].closure_glyphs(self)
  File "fontTools/subset/__init__.py", line 2071, in closure_glyphs
    layers.update(_paint_glyph_names(paint, self.table))
  File "fontTools/subset/__init__.py", line 2045, in _paint_glyph_names
    paint.traverse(colr, callback)
  File "fontTools/ttLib/tables/otTables.py", line 1549, in traverse
    stack.extend(reversed(current.getChildren(colr)))
  File "fontTools/ttLib/tables/otTables.py", line 1519, in getChildren
    return colr.LayerList.Paint[
AttributeError: 'NoneType' object has no attribute 'Paint'
```
